### ISSUE TITLE
Bot crashing when using /disconnect command on Fedora 37 x86_64

### ISSUE THREAD

**Issue by IdaCryze** [TheTipo01/YADMB#12]
Having set up everything on Fedora 37 x86_64, the bot crashes when the /disconnect command is invoked.
Below is the log:

2023-03-02 14:33:52 [LIT0] utilities.go:84:sendEmbedInteraction() InteractionRespond failed: HTTP 404 Not Found, {"message": "Unknown interaction", "code": 10062}
2023-03-02 14:33:54 [LIT0] utilities.go:249:deleteInteraction() InteractionResponseDelete failed: HTTP 404 Not Found, {"message": "Unknown Webhook", "code": 10015}
panic: runtime error: index out of range [0] with length 0

goroutine 95 [running]:
main.voiceStateUpdate(0xc0000b5880, 0xc0006bcb80)
        /home/bot/YADMB/main.go:234 +0x329
github.com/bwmarrin/discordgo.voiceStateUpdateEventHandler.Handle(0x4349464954524543?, 0x455441?, {0x9cfee0?, 0xc0006bcb80?})
        /home/bot/go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.0/eventhandlers.go:1228 +0x38
created by github.com/bwmarrin/discordgo.(*Session).handle
        /home/bot/go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.0/event.go:171 +0x16a

**Comment by TheTipo01** [comment]
The latest commit should fix the problem!
