### ISSUE TITLE
Out of range when trying to play a playlist.

### ISSUE THREAD

**Issue by negezor** [TheTipo01/YADMB#17]
Playlist: https://www.youtube.com/watch?v=oPxE4fuds94&list=PLf7kEBkHe1Cg2Ss1SqxG1fQEwQLlGboKF
```
panic: runtime error: index out of range [22] with length 22

goroutine 9 [running]:
github.com/TheTipo01/YADMB/youtube.(*YouTube).GetPlaylist(0xc0007d20f8, {0xc0007f2331, 0x22})
       /app/youtube/youtube.go:75 +0x7c5
main.downloadAndPlayYouTubeAPI(0xc000111180, {0xc0005e8d08, 0x12}, {0xc0007f2300, 0x53}, {0xc0000b8fc0, 0x7}, 0xc0003fc160, 0x0, 0x0, ...)
       /app/download.go:166 +0x118
main.downloadAndPlay(0xc000111180, {0xc0005e8d08, 0x12}, {0xc0007f2300, 0x53}, {0xc0000b8fc0, 0x7}, 0xc0003fc160, 0x0, 0x0, ...)
       /app/download.go:52 +0x4fd
main.play(0xc000111180, {0xc0007f2300, 0x53}, 0x2?, {0xc0005e8d08, 0x12}, {0xc0000b8fc0, 0x7}, 0x28?, 0x0, ...)
       /app/wrapper.go:22 +0x78e
main.playCommand(0xc000111180, 0xc0007d21a0, 0x1)
       /app/commands.go:763 +0x691
main.glob..func2(0xda5f60?, 0xc0004f6e40?)
       /app/commands.go:273 +0x1e
main.main.func1(0xc000111180, 0xc0007d21a0)
       /app/main.go:179 +0x2d2
github.com/bwmarrin/discordgo.interactionCreateEventHandler.Handle(0xc0003e07d0?, 0x6cd78a?, {0xde4a00?, 0xc0007d21a0?})
       /go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.1/eventhandlers.go:693 +0x38
created by github.com/bwmarrin/discordgo.(*Session).handle
       /go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.1/event.go:171 +0x16a

yadmb_bot_1 exited with code 2
```

**Comment by TheTipo01** [comment]
Never tested the new API with a playlist that has deleted videos!
That commit fixes the problem.

Also, nice choice of music :P
